# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniName', models.CharField(max_length=200)),
                ('uniCode', models.IntegerField()),
            ],
        ),
    ]
