# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0003_auto_20180414_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uniCode', models.IntegerField()),
                ('studentName', models.CharField(max_length=50)),
                ('studentCode', models.AutoField(primary_key=True, serialize=False)),
                ('passkey', models.CharField(max_length=160)),
            ],
        ),
    ]
