# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('uniCode', models.IntegerField()),
                ('facultyName', models.CharField(max_length=50)),
                ('facultyCode', models.AutoField(primary_key=True, serialize=False)),
                ('passkey', models.CharField(max_length=160)),
            ],
        ),
    ]
