# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('facultyID', models.IntegerField()),
                ('courseCode', models.CharField(max_length=6)),
                ('attended', models.IntegerField()),
                ('bunked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseCode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('attendance_criteria', models.IntegerField()),
            ],
        ),
    ]
