# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0006_attendance_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('facultyID', models.IntegerField()),
                ('feedback', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
    ]
