# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0007_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='srs',
            name='feedbackScore',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
