# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-15 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0009_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRS_Question',
            fields=[
                ('quesCode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('quesText', models.TextField()),
            ],
        ),
    ]
