# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRS', '0010_srs_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
